### ISSUE TITLE
Emoji Replacement

### ISSUE THREAD

**Issue by myopiangela** [heychrono/Chronobiks#3]
**Suggesting an emoji replacement for the following:**

_(1)_
From:
![image](https://user-images.githubusercontent.com/85440030/132133207-9c7013d2-bc31-44b5-8bad-ec86b22212bb.jpeg)

To:
😵 Worst

_(2)_
From:
![image](https://user-images.githubusercontent.com/85440030/132133666-929635d4-102b-4ae8-a458-37f7c459e892.jpeg)

To:
📆 Past

**Comment by heychrono** [comment]
Henlo, sure ka ba dito?
![image](https://user-images.githubusercontent.com/68635840/132136177-b25a909c-313a-4445-90c7-6ceb5ebca5ce.png)

**Comment by heychrono** [comment]
![image](https://user-images.githubusercontent.com/68635840/132136230-14aa2e88-15c9-4186-8541-ab3b27b9d7b2.png)

**Comment by myopiangela** [comment]
Yup, all good!
